name: BuildOn

on:
  push:
    branches:
      - master

jobs:
  # test:
  #   runs-on: [ windows-latest ]
  #   steps:
  #     - uses: actions/checkout@v3
  #     - name: Test
  #       run: make test

  build:
    name: Build WindowsX64
    # needs: test
    strategy:
      matrix:
        include:
          # - os: macOS
          #   arch: ARM64
          #   runner: [ self-hosted, macOS, ARM64 ]
          #   asset_path: ./release/wox-mac-arm64.dmg
          #   asset_name: wox-mac-arm64.dmg
          #   content_type: application/x-elf
          #   needs_keychain: true
          # - os: macOS
          #   arch: AMD64
          #   runner: [ self-hosted, macOS, X64 ]
          #   asset_path: ./release/wox-mac-amd64.dmg
          #   asset_name: wox-mac-amd64.dmg
          #   content_type: application/x-elf
          #   needs_keychain: true
          - os: Windows
            arch: AMD64
            asset_path: ./release/wox-windows-amd64.exe
            asset_name: wox-windows-amd64.exe
            content_type: application/x-msdownload
          # - os: Linux
          #   arch: AMD64
          #   runner: [ self-hosted, Linux ]
          #   asset_path: ./release/wox-linux-amd64
          #   asset_name: wox-linux-amd64
          #   content_type: application/x-msdownload
    runs-on: windows-2025
    steps:
      - uses: actions/checkout@v3
      - run: powershell && pwd
      - run: choco install fnm -y  --limit-output
      - run: fnm install 22 && npm -v && npm -v
      - run: npm install -g pnpm
      - run: choco install python -y --limit-output && where.exe python && python --version
      # - run: choco install cygwin -y
      - run: where.exe bash && bash --version
      # - run: choco install git -y --limit-output
      - run: choco install golang -y --limit-output && where.exe go && go version
      - run: powershell -ExecutionPolicy ByPass -c "irm https://astral.sh/uv/install.ps1 | iex"
      - run: choco install upx -y --limit-output
      - run: choco install flutter -y 
      - run: flutter config  --no-enable-fuchsia  --no-enable-ios  --no-enable-macos-desktop  --no-enable-linux-desktop
      - run: flutter doctor
      - run: bash
      - name: Build
        run: make build
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.asset_name }}
          path: ${{ matrix.asset_path }}
          retention-days: 3
      # - name: Deploy nightly release
      #   uses: WebFreak001/deploy-nightly@v3.0.0
      #   with:
      #     upload_url: https://uploads.github.com/repos/Wox-launcher/Wox/releases/127182165/assets{?name,label}
      #     release_id: 127182165
      #     asset_path: ${{ matrix.asset_path }}
      #     asset_name: ${{ matrix.asset_name }}
      #     asset_content_type: ${{ matrix.content_type }}
      #     max_releases: 1
